from abc import ABC, abstractmethod

class RenderBackend(ABC):
    @abstractmethod
    def setup(width, height, rasterize, renderer): ...
    @abstractmethod
    def set_texture_for_raster(img_path): ...
    @abstractmethod
    def add_texture_for_raster(img_path): ...
    @abstractmethod
    def rebuild_textures(renderer): ...
    @abstractmethod
    def rebuild_shaders(renderer): ...
    @abstractmethod
    def rasterize(all_tris): ...
    @abstractmethod
    def toggle_depth_view(b): ...
    @abstractmethod
    def toggle_heat_map(b): ...
    @abstractmethod
    def set_render_type(type, screen): ...
    @abstractmethod
    def set_rasterization_size(size): ...
    @abstractmethod
    def generate_cubemap_skybox(radius, texture_path, left_uvs, right_uvs, top_uvs, bottom_uvs, forward_uvs, backward_uvs): ...
    @abstractmethod
    def generate_cross_type_cubemap_skybox(radius, img_path): ...
    @abstractmethod
    def capture_pause_snapshot(): ...
    @abstractmethod
    def run_compute_shaders(tri_count): ...